### ISSUE TITLE
"[ERROR] could not locate runnable browser" when trying to open link result set

### ISSUE THREAD

**Issue by ConorAAG** [jaymoulin/docker-ddgr#2]
I have ddgr running using following command

```docker run --rm -ti jaymoulin/ddgr```

When I search for a term I get a list of results as expected. I then type, for example, `o 1` to open the first link but I get the error message:

```[ERROR] could not locate runnable browser```

This error comes from webbrowser.py. Since no browser is installed on the docker container how is ddrg supposed to open a browser!?

**Comment by jaymoulin** [comment]
This version is not supposed to open a browser. However, you probably could share your browser and X11 server for docker image to control your host's browser

**Comment by ConorAAG** [comment]
OK thanks for prompt reply.

I will look into sharing browser and X11 server.
